server:
  port: 9091
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/smartedux?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# Swagger
swagger:
  enabled: true
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false